### ISSUE TITLE
Failed to activate the atom-i18n-beta package

### ISSUE THREAD

**Issue by eaol1** [juggernautjp/atom-i18n-beta#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Linux Mint
**Thrown From**: [atom-i18n-beta](https://github.com/juggernautjp/atom-i18n-beta) package 0.1.0

### Stack Trace

Failed to activate the atom-i18n-beta package

```
At The "path" argument must be of type string. Received type undefined

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1039:7)
    at /packages/atom-i18n-beta/lib/main.js:36:12)
    at /packages/atom-i18n-beta/lib/main.js:96:15)
    at /packages/atom-i18n-beta/lib/main.js:97:27)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:756277)
    at requireModule (/usr/share/atom/resources/app/static/<embedded>:14:1191586)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3400508)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3388492)
    at /usr/share/atom/resources/app/static/<embedded>:11:3388270
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3385848)
    at /usr/share/atom/resources/app/static/<embedded>:11:3388130
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:3388073)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:385497)
    at /usr/share/atom/resources/app/static/<embedded>:11:385113
    at Config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:334641)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/static/<embedded>:11:385063)
    at PackageManager.activate (/usr/share/atom/resources/app/static/<embedded>:11:384613)
    at /usr/share/atom/resources/app/static/<embedded>:1:778470
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app/static/<embedded>:1:778955)
```

### Commands

```
```

### Non-Core Packages

```
apm-publish 0.3.2 
atom-angular-material-snippets 1.3.0 
atom-beautify 0.33.4 
atom-chs-menu 1.0.0 
atom-commander 0.12.3 
atom-html-preview 0.2.6 
atom-i18n-beta 0.1.0 
atom-ng-attr-hint 2.1.0 
atom-shortcuts 0.0.2 
atom-wrap-in-tag 0.6.0 
auto-encoding 0.7.2 
autocomplete 0.47.0 
autocomplete-angular-material 0.4.0 
autocomplete-font-awesome 1.0.2 
autocomplete-project-paths 2.2.0 
bitrix-snippets 0.3.2 
browser-plus 0.0.98 
busy-signal 2.0.1 
cdn-libs 0.1.3 
cdnjs 1.5.5 
color-picker 2.3.0 
double-tag 1.7.0 
drag-relative-path 1.2.3 
emmet 2.4.3 
figlet 0.5.4 
file-browser 0.4.1 
file-icons 2.1.47 
file-type-icons 1.3.4 
font-awesome-snippetset 0.0.6 
git-control 0.9.0 
git-plus 8.7.1 
github-atom-light-syntax 0.5.0 
google-translate-modal 1.2.2 
gz-opener 0.3.1 
html-tab 1.0.2 
ide-php 0.7.18 
intentions 2.1.1 
jquery-snippets 11.0.0 
json-converter 0.2.4 
language-csv 1.1.2 
linter 3.4.0 
linter-ui-default 3.4.1 
minimap 4.39.14 
minimap-linter 2.2.2 
minimap-pigments 0.2.2 
minimap-titles 1.15.0 
open-in-browsers 0.0.30 
open-unsupported-files 1.0.20 
pdf-view 0.73.0 
plain-simple 1.1.0 
project-viewer 1.4.0 
remote-atom 1.3.12 
simple-drag-drop-text 0.5.0 
tablr 1.8.3 
tag 0.5.0 
terminal-fusion 2.4.4 
text-manipulation 0.6.0 
unique-file-id 0.1.1 
zip-folder 3.3.0 
```

**Comment by Patricxx** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.4
**Thrown From**: [atom-i18n-beta](https://github.com/juggernautjp/atom-i18n-beta) package 0.2.0


### Stack Trace

Failed to activate the atom-i18n-beta package

```
At The "path" argument must be of type string. Received type undefined

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1039:7)
    at /packages/atom-i18n-beta/lib/main.js:36:12)
    at /packages/atom-i18n-beta/lib/main.js:96:32)
    at /packages/atom-i18n-beta/lib/main.js:98:3)
    at Module.get_Module._compile (/private/var/folders/xz/qdw5s3151s19p1_d6_k62rpc0000gn/T/AppTranslocation/097DBDC8-6E56-47CC-A67E-ADA1382DBC35/d/Atom.app/Contents/Resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/private/var/folders/xz/qdw5s3151s19p1_d6_k62rpc0000gn/T/AppTranslocation/097DBDC8-6E56-47CC-A67E-ADA1382DBC35/d/Atom.app/Contents/Resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/private/var/folders/xz/qdw5s3151s19p1_d6_k62rpc0000gn/T/AppTranslocation/097DBDC8-6E56-47CC-A67E-ADA1382DBC35/d/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
    at requireModule (/private/var/folders/xz/qdw5s3151s19p1_d6_k62rpc0000gn/T/AppTranslocation/097DBDC8-6E56-47CC-A67E-ADA1382DBC35/d/Atom.app/Contents/Resources/app/static/<embedded>:14:1191586)
    at Package.requireMainModule (/private/var/folders/xz/qdw5s3151s19p1_d6_k62rpc0000gn/T/AppTranslocation/097DBDC8-6E56-47CC-A67E-ADA1382DBC35/d/Atom.app/Contents/Resources/app/static/<embedded>:11:3402829)
    at Package.activateNow (/private/var/folders/xz/qdw5s3151s19p1_d6_k62rpc0000gn/T/AppTranslocation/097DBDC8-6E56-47CC-A67E-ADA1382DBC35/d/Atom.app/Contents/Resources/app/static/<embedded>:11:3390813)
    at /private/var/folders/xz/qdw5s3151s19p1_d6_k62rpc0000gn/T/AppTranslocation/097DBDC8-6E56-47CC-A67E-ADA1382DBC35/d/Atom.app/Contents/Resources/app/static/<embedded>:11:3390591
    at Package.measure (/private/var/folders/xz/qdw5s3151s19p1_d6_k62rpc0000gn/T/AppTranslocation/097DBDC8-6E56-47CC-A67E-ADA1382DBC35/d/Atom.app/Contents/Resources/app/static/<embedded>:11:3388169)
    at /private/var/folders/xz/qdw5s3151s19p1_d6_k62rpc0000gn/T/AppTranslocation/097DBDC8-6E56-47CC-A67E-ADA1382DBC35/d/Atom.app/Contents/Resources/app/static/<embedded>:11:3390451
    at new Promise (<anonymous>)
    at Package.activate (/private/var/folders/xz/qdw5s3151s19p1_d6_k62rpc0000gn/T/AppTranslocation/097DBDC8-6E56-47CC-A67E-ADA1382DBC35/d/Atom.app/Contents/Resources/app/static/<embedded>:11:3390394)
    at PackageManager.activatePackage (/private/var/folders/xz/qdw5s3151s19p1_d6_k62rpc0000gn/T/AppTranslocation/097DBDC8-6E56-47CC-A67E-ADA1382DBC35/d/Atom.app/Contents/Resources/app/static/<embedded>:11:385497)
    at /private/var/folders/xz/qdw5s3151s19p1_d6_k62rpc0000gn/T/AppTranslocation/097DBDC8-6E56-47CC-A67E-ADA1382DBC35/d/Atom.app/Contents/Resources/app/static/<embedded>:11:914488
    at r (/private/var/folders/xz/qdw5s3151s19p1_d6_k62rpc0000gn/T/AppTranslocation/097DBDC8-6E56-47CC-A67E-ADA1382DBC35/d/Atom.app/Contents/Resources/app/static/<embedded>:11:909094)
    at n (/private/var/folders/xz/qdw5s3151s19p1_d6_k62rpc0000gn/T/AppTranslocation/097DBDC8-6E56-47CC-A67E-ADA1382DBC35/d/Atom.app/Contents/Resources/app/static/<embedded>:14:1190909)
    at ChildProcess.<anonymous> (/private/var/folders/xz/qdw5s3151s19p1_d6_k62rpc0000gn/T/AppTranslocation/097DBDC8-6E56-47CC-A67E-ADA1382DBC35/d/Atom.app/Contents/Resources/app/static/<embedded>:14:1191115)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-i18n-beta 0.2.0 
busy-signal 2.0.1 
hey-pane 1.2.0 
Hydrogen 2.16.3 
intentions 2.1.1 
kite 0.206.0 
linter 3.4.0 
linter-ui-default 3.4.1 
mamutal91-mysyntaxtheme 0.1.0 
platformio-ide-terminal 2.10.1 
scroll-through-time 0.3.1 
teletype 0.13.4 
vizality-snippets 0.1.1 
zentabs 0.8.9 
```

**Comment by juggernautjp** [comment]
I fixed some bugs and verified that the current version (version 0.2.4) dose work.
So, update your atom-i18n-beta to version 0.2.4, and try it again.
atom-i18n-beta needs the newest Atom, so update Atom version 1.57 or later.
